/*
	ArmA 3 Wasteland
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	
	Special build for Dwarden
	
	ESABQIEXHTFRGOFR
*/
class Wasteland_Loading{idd=-1;duration=1e+011;name="Wasteland_Loading";onLoad="uiNamespace setVariable ['Wasteland_Loading', _this select 0]";class controlsBackground{class Loading:RscText{idc=-1;style=2;text=$STR_WL_Gen_LoadingUppercaseUnderscore;x=0.5-a3_sizeEx(8)/2;y=0.5-a3_sizeEx(2)/2;w=a3_sizeEx(8);h=a3_sizeEx(2);colorBackground[]={0,0,0,1};sizeEx=a3_sizeEx(2);};};};class Wasteland_ReviveStuff{idd=-1;duration=1e+011;name="Wasteland_ReviveStuff";onLoad="uiNamespace setVariable ['Wasteland_ReviveStuff', _this select 0]";class controlsBackground{
#define REVIVE_OFFSET_TOP	((SafeZoneH / 8) - (a3_sizeEx(1) + a3_sizeEx(2))) / 2
#define REVIVE_OFFSET_BOTTOM	((SafeZoneH / 8) - a3_sizeEx(1)) / 2
class StateText:RscText{idc=-1;text="INCAPACITATED";style=2;x=SafeZoneX;y=SafeZoneY+REVIVE_OFFSET_TOP;w=SafeZoneW;h=a3_sizeEx(2);sizeEx=a3_sizeEx(2);shadow=0;};class ReviveText:RscText{idc=-1;text="Waiting to be revived by teammate";style=2;x=SafeZoneX;y=SafeZoneY+REVIVE_OFFSET_TOP+a3_sizeEx(2);w=SafeZoneW;h=a3_sizeEx(1);sizeEx=a3_sizeEx(1);shadow=0;};class HintText:RscText{idc=-1;text="Press ESC to abort and respawn";style=2;x=SafeZoneX;y=SafeZoneY+SafeZoneH-REVIVE_OFFSET_BOTTOM-a3_sizeEx(1);w=SafeZoneW;h=a3_sizeEx(1);sizeEx=a3_sizeEx(1);shadow=0;};};class Controls{class ReviveMapBackground:RscText{idc=-1;x=SafeZoneX+(1/8)/4-_SPX(2);y=SafeZoneY+(1/8)/4*(getResolution select 2)/(getResolution select 3)-_SPY(2);w=0.3+_SPX(2)*2;h=0.3*(getResolution select 2)/(getResolution select 3)+_SPY(2)*2;colorBackground[]={0,0,0,1};};class ReviveMap:RscMapControl{idc=wgalb7;x=SafeZoneX+(1/8)/4;y=SafeZoneY+(1/8)/4*(getResolution select 2)/(getResolution select 3);w=0.3;h=0.3*(getResolution select 2)/(getResolution select 3);};};};class Wasteland_RespawnIn{idd=-1;duration=1e+011;name="Wasteland_RespawnIn";onLoad="uiNamespace setVariable ['Wasteland_RespawnIn', _this select 0]";class controlsBackground{class RespawnText:RscText{idc=wgm6mm;style=2;text="";x=0.5-a3_sizeEx(14)/2;y=0.5-a3_sizeEx(2)/2+0.2;w=a3_sizeEx(14);h=a3_sizeEx(2);colorBackground[]={0,0,0,1};sizeEx=a3_sizeEx(2);};class HintBackground:RscText{idc=-1;x=0.1-0.01*(safezoneH/safezoneW);y=0.5+0.3-0.01;w=0.8+0.02;h=0.18+0.02;colorBackground[]={0,0,0,1};};class HintImage:RscPicture{idc=wg1pj7;text="";x=0.1;y=0.5+0.3;w=0.18*(safezoneH/safezoneW);h=0.18;};class HintText:RscStructuredText{idc=wgy89h;text="";x=0.1+0.18*(safezoneH/safezoneW)+0.01*(safezoneW/safezoneH);y=0.5+0.3-0.015;w=0.8-0.18*(safezoneH/safezoneW)-0.01*(safezoneW/safezoneH);h=0.20;};};};class Wasteland_Teamkiller{idd=-1;duration=1e+011;name="Wasteland_Teamkiller";onLoad="uiNamespace setVariable ['Wasteland_Teamkiller', _this select 0]";class controlsBackground{class TeamkillerText:RscStructuredText{idc=-1;x=0;y=0.25;w=1;h=0.2;text=$STR_WL_HUD_TeamkillerMessage;shadow=2;colorBackground[]={0,0,0,0.5};class Attributes{align="center";};};};};class Wasteland_Welcome{idd=-1;duration=1e+011;name="Wasteland_Welcome";onLoad="uiNamespace setVariable ['Wasteland_Welcome', _this select 0]";class controlsBackground{class WelcomeText:RscStructuredText{idc=wgx4ri;x=0.2;y=0.1;w=0.6;h=0.9;text="";shadow=2;class Attributes{align="center";};};};};