/*
	ArmA 3 Wasteland
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	
	Special build for Dwarden
	
	ESABQIEXHTFRGOFR
*/
if(wgwa58)then{systemChat wgv8c1;}else{wgwa58=true;private["_0cv","_04v"];_0cv=wgm1lv;_04v=_this select 0;if(!(isNull _0cv)&&(alive _0cv||typeOf _0cv=="Land_DieselGroundPowerUnit_01_F")&&!(_0cv getVariable "R3F_LOG_disabled"))then{if(isNull(_0cv getVariable "R3F_LOG_est_transporte_par")&&(isNull(_0cv getVariable "R3F_LOG_est_deplace_par")||(!alive(_0cv getVariable "R3F_LOG_est_deplace_par"))))then{if(_0cv distance _04v<=30)then{if!(_0cv call wgbqap)exitWith{_0ho=(_0cv call wgdtln);if(_0ho call wgr44t)then{hint format["This object is locked by %1 and cannot be towed",name _0ho];}else{hint "This object is locked and cannot be towed";};wgwa58=false;};if(_0cv getVariable["object_locked",false])exitWith{hint "This object is locked and cannot be towed";wgm1lv=objNull;wgwa58=false;};_0dw=_04v;_0ew=1;while{!isNull(_0dw getVariable["R3F_LOG_est_transporte_par",objNull])}do{_0ew=_0ew+1;_0dw=_0dw getVariable["R3F_LOG_est_transporte_par",objNull];};_0dw=_0cv;_0fw=1;while{!isNull(_0dw getVariable["R3F_LOG_remorque",objNull])}do{_0fw=_0fw+1;_0dw=_0dw getVariable["R3F_LOG_remorque",objNull];};if(_0ew+_0fw<=3)then{_04v setVariable["R3F_LOG_remorque",_0cv,true];_0cv setVariable["R3F_LOG_est_transporte_par",_04v,true];player attachTo[_04v,[(boundingBox _04v select 1 select 0),(boundingBox _04v select 0 select 1)+1,(boundingBox _04v select 0 select 2)-(boundingBox player select 0 select 2)]];player setDir 270;player setPos(getPos player);if(!local _0cv)then{};player switchMove "AinvPknlMstpSnonWnonDnon_medic_1";player playMove "AinvPknlMstpSnonWnonDnon_medic_1";sleep 2;_05v=({if(_0cv isKindOf(_x select 0))exitWith{_x select 1}}forEach wguboy);if(isNil{_05v})then{_05v=0;};_06v=_04v;_07v=_0cv;_08v=boundingBoxReal _06v;_09v=boundingBoxReal _07v;_0aw=-(_09v select 1 select 1);_0bw=(_08v select 0 select 1);_0cw=(_08v select 0 select 2)-(_09v select 0 select 2);_07v attachTo[_06v,[0,_0aw+_0bw+_05v,_0cw]];wgm1lv=objNull;detach player;if(_0cv isKindOf "StaticWeapon")then{private["_0wv"];_0wv=((_0cv weaponDirection(weapons _0cv select 0))select 0)atan2((_0cv weaponDirection(weapons _0cv select 0))select 1);if!(_0cv isKindOf "D30_Base")then{_0wv=_0wv+180;};wgbeie=[_0cv,(getDir _0cv)-_0wv];if(local _0cv)then{["wgbeie",wgbeie]spawn wguu3i;}else{publicVariable "wgbeie";};};sleep 3;}else{systemChat "Cannot tow like this, chain is too long (Max 3 vehicles in chain)";};}else{systemChat format[wgtm4w,getText(configFile>>"CfgVehicles">>(typeOf _0cv)>>"displayName")];};}else{systemChat format[wg35rd,getText(configFile>>"CfgVehicles">>(typeOf _0cv)>>"displayName")];};};wgwa58=false;};