/*
	ArmA 3 Wasteland
	Code written by Sa-Matra
	Using this code without Sa-Matra's direct permission is forbidden
	
	
	Special build for Dwarden
	
	ESABQIEXHTFRGOFR
*/
_08h=_this;if!(_08h getVariable["show_me_on_map",true])then{_08h setVariable["show_me_on_map",false,true];};if(count(_08h getVariable["invites",[]])>0)then{_08h setVariable["invites",_08h getVariable["invites",[]],true];};{_08h removeWeapon _x}forEach(assignedItems _08h);removeUniform _08h;removeVest _08h;removeBackpack _08h;removeAllWeapons _08h;removeHeadgear _08h;removeGoggles _08h;_08h addWeapon "ItemMap";_08h addWeapon "ItemCompass";_08h addWeapon "ItemRadio";_08h addWeapon "ItemWatch";_01u=(wghrav in["76561198018217855"]);_03="";_0s="";_0af="";_04="";_0v="";_0ml="";_02u=false;switch(playerSide)do{case blufor:{_0v=["hgun_P07_F"]select(floor random 1);_0ml="30Rnd_9x21_Mag";_03=["U_B_CombatUniform_mcam_tshirt"]select(floor random 1);if(random 10<1)then{_03="U_B_CTRG_1";_0s="H_Cap_blk";_0v="hgun_P07_snds_F";if(random 10<1)then{_03="U_B_CombatUniform_mcam_vest";_0s="H_Watchcap_blk";_0v="SMG_02_F";_0af="G_Tactical_Clear";};};};case opfor:{_0v=["hgun_Rook40_F"]select(floor random 1);_0ml="30Rnd_9x21_Mag";_03=["U_O_CombatUniform_ocamo"]select(floor random 1);if(random 10<1)then{_03="U_O_CombatUniform_oucamo";_0s="H_MilCap_gry";_0v="hgun_Rook40_snds_F";if(random 10<1)then{_03="U_O_OfficerUniform_ocamo";_0v="hgun_PDW2000_F";_0af="G_Tactical_Black";_0s="H_Beret_blk";};};};case independent:{_0v="hgun_ACPC2_F";_0ml="9Rnd_45ACP_Mag";_03=["U_IG_Guerilla2_2","U_IG_Guerilla2_3"]select floor(random 2);if(random 10<1)then{_0v="hgun_ACPC2_snds_F";switch(floor(random 3))do{case 0:{_03="U_Marshal";_0s="H_Cap_blk_ION";};case 1:{_03="U_C_Poor_1";_0s="H_Cap_blu";};case 2:{_03="U_C_HunterBody_grn";_0s="H_Hat_checker";_0af="G_Spectacles_Tinted";};};if(random 10<1)then{_03="U_IG_leader";_0s="H_Booniehat_dgtl";_0v="SMG_01_F";_0ml="30Rnd_45ACP_Mag_SMG_01";_03u=["G_Aviator","G_Lowprofile"]select floor(random 2);};}else{if(random 5<1)then{_0s=["H_Bandanna_cbr","H_Bandanna_gry","H_Bandanna_sgg","H_BandMask_blk","H_Cap_tan","H_StrawHat_dark"]select floor(random 6);};};};};if(_04!="")then{_08h addVest _04;};if(_03!="")then{_08h addUniform _03;};if(_0s!="")then{_08h addHeadgear _0s;}else{removeHeadgear _08h;};if(_0af!="")then{_08h addGoggles _0af;}else{removeGoggles _08h;};if(_02u)then{_08h addItem "FirstAidKit"};_08h addMagazine _0ml;_08h addWeapon _0v;_08h selectWeapon _0v;if(!isNil{settings_disableFatigue})then{if(settings_disableFatigue)then{player enableFatigue false;}};if(call wgjomf)then{_04u=(switch(playerSide)do{case blufor:{"Chemlight_blue"};case opfor:{"Chemlight_red"};default{"Chemlight_green"};});_08h addMagazines[_04u,1];hint parseText format["You spawned with<br/><img image='%1' size='4'/><br/>a chemlight<br/>(Press %3 to throw)",getText(configFile>>"CfgMagazines">>_04u>>"picture"),1,actionKeysNames "Throw"];};true call wgegkd;wgcnta=objNull;wgwsvk=100;wgsna4=100;wg1id4=100;if(_01u)then{wg1id4=500+ceil(random 500/5)*5};wgt7bi=[[],[],[],[]];call wg3n3u;